namespace: openclaw

image:
  repository: alpine/openclaw
  tag: main
  pullPolicy: IfNotPresent

service:
  port: 18789

resources:
  requests:
    cpu: 400m
    memory: 786Mi
  limits:
    cpu: 2000m
    memory: 3Gi

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetPendingRequests: 100

ingress:
  enabled: true
  host: openclaw.localhost.com
  ingressClassName: traefik

gatewayAuthToken: "rjifWEGMs0WYwXc6oCPEPGDr3jilYZdpgMvluLZ2sVo="

loadgen:
  enabled: false
  image: curlimages/curl:8.8.0
  requests: 2000
  concurrency: 20
  url: http://openclaw.localhost.com/

networkPolicy:
  enabled: true