apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: {{ .Values.namespace }}
data:
  openclaw.json: |
    {
      gateway: {
        bind: "lan",
        auth: {
          mode: "token",
          token: "${OPENCLAW_GATEWAY_TOKEN}",
        },
        controlUi: {
          basePath: "/",
        },
      },
    }
