apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw-serverless
spec:
  replicas: 0
  selector:
    matchLabels:
      app: openclaw
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      containers:
        - name: openclaw-serverless
          image: alpine/openclaw:main
          ports:
            - containerPort: 18789
          volumeMounts:
            - name: data
              mountPath: /home/node/.openclaw
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openclaw-pvc
    

         


